webtalk_init -webtalk_dir D:/digitalElctronics/Digital-Electronics1/LABS/07-ffs/flipFlops/flipFlops.sim/sim_1/behav/xsim/xsim.dir/tb_d_ff_arst_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 30 20:42:59 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "588f2464-f99a-4d63-b493-35b34f5a3a4e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "833a16b24c78426ba298a14c1850076b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6388_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4204560843 -regid "" -xml D:/digitalElctronics/Digital-Electronics1/LABS/07-ffs/flipFlops/flipFlops.sim/sim_1/behav/xsim/xsim.dir/tb_d_ff_arst_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/digitalElctronics/Digital-Electronics1/LABS/07-ffs/flipFlops/flipFlops.sim/sim_1/behav/xsim/xsim.dir/tb_d_ff_arst_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/digitalElctronics/Digital-Electronics1/LABS/07-ffs/flipFlops/flipFlops.sim/sim_1/behav/xsim/xsim.dir/tb_d_ff_arst_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
